name: Build & Upload JAR to GCP

on:
  push:
    branches: [ "main" ]   # triggers on push to main branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # 1️⃣ Checkout your code
    - name: Checkout repository
      uses: actions/checkout@v4

    # 2️⃣ Setup Java (adjust version if needed)
    - name: Set up JDK 11
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '11'

    # 3️⃣ Build with Maven
    - name: Build JAR with Maven
      run: mvn clean package

    # 4️⃣ Upload JAR to GCP bucket
    - name: Upload to Google Cloud Storage
      uses: google-github-actions/upload-cloud-storage@v2
      with:
        credentials_json: '${{ secrets.GCP_SA_KEY }}'
        path: 'target/*.jar'
        destination: 'gs://airflow-dags-dr'