name: Build and Upload JAR to GCP

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 11
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '11'

      - name: Build with Maven
        run: mvn clean package

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      - name: Upload JAR to GCP bucket
        uses: google-github-actions/upload-cloud-storage@v2
        with:
          path: target/spark-example-0.0.1-SNAPSHOT.jar  # ✅ use exact file name
          destination: airflow-dags-dr                   # ✅ replace with your bucket name
